### PR TITLE
Update to Julia v1 CxxWrap v0.7 and MOI v0.6

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by blegat** [comment]
I have got the error
```
/home/travis/julia/bin/julia: symbol lookup error: /home/travis/build/blegat/SDPA.jl/deps/usr/lib/libsdpawrap.so: undefined symbol: _ZN5jlcxx10julia_typeERKSsS1_
```
on the Linux build. @barche Any idea what might be wrong ? It was working find on CxxWrap v0.6

**Comment by barche** [comment]
I think the problem is due to the changed location of the cmake config files, I now have `${JlCxx_DIR}/../` in my `CMAKE_INSTALL_RPATH` for QML.jl.

**Comment by blegat** [comment]
Thanks for the response ! I tried it in https://github.com/blegat/SDPA.jl/pull/11/commits/dc39df9f9e0f00906b0ba6a4f8742b622049a179 (is it the change you expected ?) but I still get the same error.
What is strange is that it works on my computer (Arch Linux) but on on Travis, it might be because of the hack I have done in the .travis.yml script to update GCC but it does not seem likely :/

**Comment by barche** [comment]
Yes, but upon further inspection, I think my advice was wrong, and the correct path is actually one more level up. But there is a better way to find the correct path:

```cmake
get_target_property(JlCxx_location JlCxx::cxxwrap_julia LOCATION)
get_filename_component(JlCxx_location ${JlCxx_location} DIRECTORY)
set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib;${JlCxx_location}")
```

This should always be correct, even when the directory is laid out differently from a standard install.

**Comment by barche** [comment]
I see it still fails, I think it is because of an incompatibility with the libcxxwrap-julia binary. These have as `julia_type` signature:
```c++
jlcxx::julia_type(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

while the travis build is looking for:
```c++
jlcxx::julia_type(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

This might be solved by the `-D_GLIBCXX_USE_CXX11_ABI=1` flag.

Ideally, the C++ part should be split off into a separate repository, where BinaryBuilder can be used to build binaries of both SPDA and the wrapper, that way everything is built by the same compiler in a way that is guaranteed to be compatible with the official Julia binaries.

**Comment by blegat** [comment]
> This might be solved by the `-D_GLIBCXX_USE_CXX11_ABI=1` flag.

Thanks for the help ! I will try that :)

> Ideally, the C++ part should be split off into a separate repository, where BinaryBuilder can be used to build binaries of both SPDA and the wrapper, that way everything is built by the same compiler in a way that is guaranteed to be compatible with the official Julia binaries.

That is the plan once this PR is done :) Do you have an example of package using CxxWrap with BinaryBuilder ?

**Comment by barche** [comment]
Taking a quick look at https://github.com/jstrube/LCIO.jl it looks to me like @jstrube has the best example so far :)

**Comment by jstrube** [comment]
Yes, feel free to take a look and ping me if you have questions. I use a three-part process. One repo to build the binary by itself (LCIOBuilder), one repo to build the wrapper code (LCIOWrapBuilder) and one repo for the julia code. Works quite well.

**Pull request merged**
